---
_format_version: "1.1"

services:
- name: httpbin
  url: https://httpbin.org/anything

routes:
- hosts: []
  methods: []
  name: httpbin
  paths:
  - /
  preserve_host: false
  regex_priority: 1
  service: httpbin
  strip_path: false
  # plugins:
  # - name: aws-sns
  #   config:
  #     topic_arn: arn:aws:sns:us-east-1:000000000000:NotifyMe
  #     aws_region: us-east-1
